BEGIN;

ALTER TABLE asset_item_types
    ADD COLUMN IF NOT EXISTS group_id BIGINT,
    ADD COLUMN IF NOT EXISTS packaged_volume DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS mass DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS capacity DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS portion_size INT,
    ADD COLUMN IF NOT EXISTS published BOOLEAN,
    ADD COLUMN IF NOT EXISTS market_group_id BIGINT,
    ADD COLUMN IF NOT EXISTS graphic_id BIGINT,
    ADD COLUMN IF NOT EXISTS race_id BIGINT,
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE market_prices
    ADD COLUMN IF NOT EXISTS adjusted_price DOUBLE PRECISION;

COMMIT;
